version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
    depends_on:
      - postgres
    command: npm run dev

  postgres:
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
